// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjB1sJTTDfA7x28UDpLdLTDR-lwCH91lU',
    appId: '1:552339039192:web:75260c77870facd6a548ad',
    messagingSenderId: '552339039192',
    projectId: 'keri-challenge',
    authDomain: 'keri-challenge.firebaseapp.com',
    databaseURL: 'https://keri-challenge-default-rtdb.firebaseio.com',
    storageBucket: 'keri-challenge.appspot.com',
    measurementId: 'G-LC4E8VQ93F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1aIEHENKuUYehmP3D0qazN2KzRPp7xk',
    appId: '1:552339039192:android:b89661691081bee3a548ad',
    messagingSenderId: '552339039192',
    projectId: 'keri-challenge',
    databaseURL: 'https://keri-challenge-default-rtdb.firebaseio.com',
    storageBucket: 'keri-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzlI3vuIkKRZAxU2zSdyUUjMhVIwUdAfg',
    appId: '1:552339039192:ios:47444cd0dedd3acaa548ad',
    messagingSenderId: '552339039192',
    projectId: 'keri-challenge',
    databaseURL: 'https://keri-challenge-default-rtdb.firebaseio.com',
    storageBucket: 'keri-challenge.appspot.com',
    iosBundleId: 'com.example.keriChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzlI3vuIkKRZAxU2zSdyUUjMhVIwUdAfg',
    appId: '1:552339039192:ios:6c62f567942d3d90a548ad',
    messagingSenderId: '552339039192',
    projectId: 'keri-challenge',
    databaseURL: 'https://keri-challenge-default-rtdb.firebaseio.com',
    storageBucket: 'keri-challenge.appspot.com',
    iosBundleId: 'com.example.keriChallenge.RunnerTests',
  );
}
